spec:
  structures:
    - content_blocks
  label: FAQ Section
  description: Frequently asked questions with accordion
  icon: help
  tags: []

define:
  title: FAQ
  faq:
    - question: Sample question?
      answer: Sample answer

blueprint:
  title: Frequently Asked Questions
  faq:
    - question: "How secure is my design data?"
      answer: "We use industry-standard encryption and secure storage practices to protect your creative assets. All files are encrypted with AES-256, and our servers are regularly monitored and updated to prevent vulnerabilities."
    - question: "Is there a free trial for design services?"
      answer: "Yes, we offer a 14-day free trial for our design platform with access to core features for logo design, 3D modelling, or website prototyping—no credit card required."

_inputs:
  title:
    type: text
  faq:
    type: array
  faq[*].question:
    type: text
  faq[*].answer:
    type: text
