spec:
  structures:
    - content_blocks
  label: Pricing Section
  description: Pricing tiers display
  icon: payments
  tags: []

define:
  title: Pricing
  plans:
    - title: Basic Plan
      tag: Most popular
      content: One designer, 5 days a month
      cta: Start free trial
      price: 999
      services:
        - item: Access to basic services
        - item: Basic assets and logos

blueprint:
  title: We do design retainers
  plans:
    - title: Basic plan
      tag: Most popular
      content: One designer, 5 days a month
      cta: Start free trial
      price: 999
      services:
        - item: Access to basic services
        - item: Basic assets and logos
        - item: Up to 10 individual assets
    - title: Enterprise plan
      tag: Best value
      content: One team, 5 days a month
      cta: Enquire now
      price: 2999
      services:
        - item: All basic plan services
        - item: 100 assets
        - item: Advanced reporting

_inputs:
  title:
    type: text
  plans:
    type: array
  plans[*].title:
    type: text
  plans[*].tag:
    type: text
  plans[*].content:
    type: text
  plans[*].cta:
    type: text
  plans[*].price:
    type: number
  plans[*].services:
    type: array
  plans[*].services[*].item:
    type: text
