spec:
  structures:
    - content_blocks
  label: Testimonials Section
  description: Grid of customer testimonials
  icon: format_quote
  tags: []

define:
  title: Client Testimonials
  testimonials:
    - quote: Great service!
      handle: username

blueprint:
  title: Clients ♥ us
  testimonials:
    - quote: "Sent over a logo request and had a polished concept in minutes—this team is pure magic!"
      handle: daviscarder
    - quote: "Clicked a few buttons in the 3D design tool, and boom—my model came to life!"
      handle: kadinwestervelt

_inputs:
  title:
    type: text
  testimonials:
    type: array
  testimonials[*].quote:
    type: text
  testimonials[*].handle:
    type: text
