spec:
  structures:
    - content_blocks
  label: Services Carousel
  description: Carousel showcasing services
  icon: view_carousel
  tags: []

define:
  title: Our Services
  items:
    - title: Service Title
      content: <strong>Service description</strong>
      cta: Learn More
      image: /content-images/blackspike-wallpaper-01.avif
      image_alt: Service image

blueprint:
  title: Our Services
  items:
    - title: We create timeless visual identities
      content: <strong>Great companies adapt and grow.</strong>
      cta: Call us
      image: /content-images/blackspike-wallpaper-01.avif
      image_alt: ""

_inputs:
  title:
    type: text
  items:
    type: array
  items[*].title:
    type: text
  items[*].content:
    type: html
  items[*].cta:
    type: text
  items[*].image:
    type: image
  items[*].image_alt:
    type: text
